# Copyright (c) 2026 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

from enum import Enum

class TrainingEvent(Enum):
    """
    Training Event enum generated by autoPyTorch during the search process.
    """
    TRAIN_LOSS = "training"
    TRAIN_EPOCH_AVGLOSS = "training_epoch"
    VAL_LOSS = "validation"
    VAL_EPOCH_AVGLOSS = "validation_epoch"
    TEST_LOSS = "test"
    TEST_EPOCH_AVGLOSS = "test_epoch"

    def __str__(self) -> str:
        parts = [w.lower() for w in self.name.split("_")]
        parts = ["avg_loss" if w == "avgloss" else w for w in parts]
        parts[0] = parts[0].capitalize()
        return "/".join(parts)

    @classmethod
    def from_tag(cls, name: str) -> 'TrainingEvent':
        """
        Parse an event tag into a training event.

        Parameters
        ----------
        name: str
            The name of the event.

        Returns
        -------
        TrainingEvent
            Corresponding `TrainingEvent`.
        """
        name = name.replace("avg_loss", "avgloss").replace("/", "_").upper()
        return cls[name]

class PipelineEvent(Enum):
    LOSS = "opt_loss"
    TRAIN_LOSS = "train_loss"
    VAL_LOSS = "validation_loss"
    TEST_LOSS = "test_loss"
    CONFIG = "configuration"
    BUDGET = "budget"
    STATUS = "status"

    def __str__(self):
        pipeline_suffix = "/".join([s.capitalize() for s in self.name.split("_")])
        return f"Pipeline/{pipeline_suffix}"

    @classmethod
    def from_tag(cls, name: str) -> 'PipelineEvent':
        """
        Parse a pipeline event tag into a `PipelineEvent`.

        Parameters
        ----------
        name: str
            The name of the pipeline event.

        Returns
        -------
        PipelineEvent
            Corresponding `PipelineEvent`.
        """
        name = name.replace("Pipeline/", "").upper().replace("/", "_")
        return cls[name]

    @classmethod
    def from_metric(cls, tag: str) -> '(PipelineEvent, str)':
        """
        Converts a pipeline event string along with its metric
        into a tuple of `PipelineEvent` and `str`. This performs
        a greedy search that finds the first match of the
        pipeline event name.

        Parameters
        ----------
        tag: str
            The pipeline event with the metric.

        Returns
        -------
        (PipelineEvent, str)
            A tuple of the found PipelineEvent and the associated
            name of the metric.

        Raises
        ------
        KeyError
            Raised when the no pipeline event matches the query.
        """
        parts = tag.split("/")
        assert parts[0] == "Pipeline", "tag must be a pipeline event"
        event = None
        metric_str = None

        for i in range(1, len(parts) + 1):
            joined = "/".join(parts[:i])
            try:
                event = cls.from_tag(joined)
                metric_str = parts[i:]
            except KeyError:
                continue
        if event is None:
            raise KeyError(f"Pipeline Event for '{tag}' not found")
        return (event, "/".join(metric_str))
